[package]
name = "yggdrasil-agent"
version = "0.1.0"
authors = ["Dreae <dreae@dreae.onl>"]

[dependencies]
getopts = "0.2.14"

[dependencies.nickel]
version = "=0.7"

[dependencies.hyper]
version = "=0.6"
